@extends('layouts.partials.body')
@section('content')
<body>
    @include('layouts.partials.desa')
    @include('layouts.partials.agenda')
    @include('layouts.partials.berita') 
</body>
  @include('layouts.partials.footer')
@endsection